# Generated by Django 6.0.5 on 2026-06-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
