# Generated by Django 6.0.5 on 2026-06-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_prescriptionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('ORDER_CREATED', 'OrderCreated'), ('PRESCRIPTION_REVIEW', 'Prescription Review'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=30),
        ),
    ]
